#!/bin/bash
set -euo pipefail

READER_USER="${SANDBOX_READER_USER:-sandbox_reader}"
READER_PASSWORD="${SANDBOX_READER_PASSWORD:-change-me-sandbox-password}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${READER_USER}') THEN
            CREATE ROLE ${READER_USER} LOGIN PASSWORD '${READER_PASSWORD}';
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${READER_USER};
    GRANT USAGE ON SCHEMA public TO ${READER_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${READER_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${READER_USER};
    REVOKE CREATE ON SCHEMA public FROM PUBLIC;
    REVOKE CREATE ON SCHEMA public FROM ${READER_USER};
EOSQL
