# Generated by Django 5.1.8 on 2026-08-16 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema_sql', models.TextField()),
                ('seed_sql', models.TextField()),
                ('preview', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasetlar',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField()),
                ('task', models.TextField()),
                ('hints', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('require_row_order', models.BooleanField(default=False)),
                ('require_column_order', models.BooleanField(default=False)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.module')),
            ],
            options={
                'verbose_name': 'Mashq',
                'verbose_name_plural': 'Mashqlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.dataset')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Mashq dataseti',
                'verbose_name_plural': 'Mashq datasetlari',
                'unique_together': {('exercise', 'dataset')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='exercises.ExerciseDataset', to='exercises.dataset'),
        ),
        migrations.CreateModel(
            name='ExerciseExpectedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('columns', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expected_result', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Kutilgan natija',
                'verbose_name_plural': 'Kutilgan natijalar',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sql_query', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('result_preview', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('execution_ms', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mashq urinishi',
                'verbose_name_plural': 'Mashq urinishlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'exercise', '-created_at'], name='exercises_e_student_a024ee_idx'), models.Index(fields=['exercise', 'is_correct'], name='exercises_e_exercis_a733df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['module', 'is_published', 'order'], name='exercises_e_module__858e29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('module', 'slug')},
        ),
    ]
