# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_exercise_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="kind",
            field=models.CharField(
                choices=[("sql", "SQL"), ("quiz", "Test / quiz")],
                default="sql",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="quiz_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Quiz variantlari, masalan: ["A) ...", "B) ..."]',
            ),
        ),
    ]
