# Generated by Django 6.1 on 2026-08-27 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='editorial',
            field=models.TextField(blank=True, help_text='To‘g‘ri yechgandan keyin ko‘rsatiladigan yechim yo‘riqnomasi (o‘zbekcha)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_skill_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Modul oxiridagi bilimsini tekshirish testi'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', 'O‘rta'), ('hard', 'Qiyin')], db_index=True, default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='kind',
            field=models.CharField(choices=[('sql', 'SQL'), ('quiz', 'Test')], default='sql', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='quiz_options',
            field=models.JSONField(blank=True, default=list, help_text='Test variantlari, masalan: ["A) ...", "B) ..."]'),
        ),
        migrations.CreateModel(
            name='ExerciseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_comments', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Masala izohi',
                'verbose_name_plural': 'Masala izohlari',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['exercise', 'created_at'], name='exercises_e_exercis_096006_idx')],
            },
        ),
    ]
