# Generated by Django 5.1.8 on 2026-08-16 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False, help_text='Talabalar ro‘yxatida ko‘rinsinmi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_published', 'is_visible', 'order'], name='courses_cou_is_publ_a4db4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('content', models.TextField(help_text='Uzbek tilidagi boy matn (HTML)')),
                ('sql_examples', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.module')),
            ],
            options={
                'verbose_name': 'Ma’ruza',
                'verbose_name_plural': 'Ma’ruzalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kursga yozilish',
                'verbose_name_plural': 'Kursga yozilishlar',
                'indexes': [models.Index(fields=['course', 'student'], name='courses_cou_course__211236_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='uniq_student_course_enrollment')],
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'is_published', 'order'], name='courses_mod_course__c19deb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['module', 'is_published', 'order'], name='courses_lec_module__7cb00a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('module', 'slug')},
        ),
    ]
