# Generated by Django 6.1 on 2026-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='premium_price',
            field=models.PositiveIntegerField(default=50000, help_text='Kurs premium narxi (so‘m). Admin orqali o‘zgartiriladi.'),
        ),
    ]
