"""Canonical catalog of the initial 20 badges (SVG artwork under static/badges/)."""

from __future__ import annotations

from apps.badges.models import Badge
from apps.badges.topics import TOPIC_JOIN, TOPIC_WINDOW

# rarity: common | rare | epic | legendary
BADGE_DEFINITIONS: list[dict] = [
    {
        "slug": "first-step",
        "name": "First Step",
        "description": "Birinchi masalangizni yechdingiz. Sayohat boshlandi!",
        "category": Badge.Category.PROBLEM,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 1,
        "sort_order": 1,
    },
    {
        "slug": "problem-solver",
        "name": "Problem Solver",
        "description": "10 ta masala — mustahkam start.",
        "category": Badge.Category.PROBLEM,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 10,
        "sort_order": 2,
    },
    {
        "slug": "rising-coder",
        "name": "Rising Coder",
        "description": "25 ta masala — ritm oshmoqda.",
        "category": Badge.Category.PROBLEM,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 25,
        "sort_order": 3,
    },
    {
        "slug": "challenge-hunter",
        "name": "Challenge Hunter",
        "description": "50 ta masala — haqiqiy ovchi.",
        "category": Badge.Category.PROBLEM,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 50,
        "sort_order": 4,
    },
    {
        "slug": "sql-explorer",
        "name": "SQL Explorer",
        "description": "Kamida 3 xil SQL mavzusidan masala yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.DISTINCT_SQL_TOPICS,
        "requirement_value": 3,
        "sort_order": 5,
    },
    {
        "slug": "join-master",
        "name": "JOIN Master",
        "description": "5 ta JOIN masalasini muvaffaqiyatli yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_JOIN},
        "sort_order": 6,
    },
    {
        "slug": "window-wizard",
        "name": "Window Wizard",
        "description": "5 ta Window Function masalasini yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_WINDOW},
        "sort_order": 7,
    },
    {
        "slug": "python-starter",
        "name": "Python Starter",
        "description": "5 ta Python masalasini yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": "python_any"},
        "sort_order": 8,
    },
    {
        "slug": "streak-3",
        "name": "3-Day Streak",
        "description": "3 kun ketma-ket o‘rganish faoliyati.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 3,
        "sort_order": 9,
    },
    {
        "slug": "streak-7",
        "name": "7-Day Streak",
        "description": "7 kunlik zanjir — odat shakllanmoqda.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 7,
        "sort_order": 10,
    },
    {
        "slug": "streak-30",
        "name": "30-Day Streak",
        "description": "30 kunlik zanjir — haqiqiy izchillik.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 30,
        "sort_order": 11,
    },
    {
        "slug": "first-lesson",
        "name": "First Lesson",
        "description": "Birinchi darsni tugatting.",
        "category": Badge.Category.LEARNING,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.LESSONS_COMPLETED,
        "requirement_value": 1,
        "sort_order": 12,
    },
    {
        "slug": "knowledge-seeker",
        "name": "Knowledge Seeker",
        "description": "10 ta darsni tugatting.",
        "category": Badge.Category.LEARNING,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.LESSONS_COMPLETED,
        "requirement_value": 10,
        "sort_order": 13,
    },
    {
        "slug": "course-finisher",
        "name": "Course Finisher",
        "description": "Butun bir nashr etilgan kursdagi barcha darslarni tugatting.",
        "category": Badge.Category.LEARNING,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.COURSE_COMPLETED,
        "requirement_value": 1,
        "sort_order": 14,
    },
    {
        "slug": "top-10",
        "name": "Top 10",
        "description": "Reytingda top-10 ga chiqing (tarixiy yutuq).",
        "category": Badge.Category.COMPETITION,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOP_RANK,
        "requirement_value": 10,
        "sort_order": 15,
    },
    {
        "slug": "top-3",
        "name": "Top 3",
        "description": "Reytingda top-3 ga chiqing.",
        "category": Badge.Category.COMPETITION,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.TOP_RANK,
        "requirement_value": 3,
        "sort_order": 16,
    },
    {
        "slug": "number-one",
        "name": "#1",
        "description": "Reytingda birinchi o‘ringa chiqing.",
        "category": Badge.Category.COMPETITION,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.TOP_RANK,
        "requirement_value": 1,
        "sort_order": 17,
    },
    {
        "slug": "perfect-week",
        "name": "Perfect Week",
        "description": "Bir haftaning 7 kunida ham o‘rganish faoliyati.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.PERFECT_WEEK,
        "requirement_value": 7,
        "sort_order": 18,
    },
    {
        "slug": "night-coder",
        "name": "Night Coder",
        "description": "Tungi o‘rganish soatlarida 10 ta faoliyat.",
        "category": Badge.Category.PLATFORM,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.NIGHT_ACTIVITY,
        "requirement_value": 10,
        "sort_order": 19,
    },
    {
        "slug": "legend",
        "name": "Legend",
        "description": "Boshqa 19 badge dan kamida 15 tasini yuting.",
        "category": Badge.Category.PLATFORM,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.BADGES_EARNED,
        "requirement_value": 15,
        "requirement_meta": {"exclude_slugs": ["legend"]},
        "sort_order": 20,
    },
]


def ensure_badges() -> int:
    """Upsert the 20 badge definitions. Returns count of definitions."""
    for spec in BADGE_DEFINITIONS:
        Badge.objects.update_or_create(
            slug=spec["slug"],
            defaults={
                "name": spec["name"],
                "description": spec["description"],
                "category": spec["category"],
                "icon_path": f"badges/{spec['slug']}.svg",
                "rarity": spec.get("rarity") or "common",
                "requirement_type": spec["requirement_type"],
                "requirement_value": spec["requirement_value"],
                "requirement_meta": spec.get("requirement_meta") or {},
                "sort_order": spec["sort_order"],
                "is_active": True,
            },
        )
    return len(BADGE_DEFINITIONS)
