"""Canonical catalog of the initial 20 badges (SVG artwork under static/badges/)."""

from __future__ import annotations

from apps.badges.models import Badge
from apps.badges.topics import (
    TOPIC_CASE,
    TOPIC_CTE,
    TOPIC_GROUP,
    TOPIC_JOIN,
    TOPIC_SELECT,
    TOPIC_SUBQUERY,
    TOPIC_WINDOW,
)

# rarity: common | rare | epic | legendary
BADGE_DEFINITIONS: list[dict] = [
    {
        "slug": "first-step",
        "name": "First Step",
        "description": "Birinchi masalangizni yechdingiz. Sayohat boshlandi!",
        "category": Badge.Category.PROBLEM,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 1,
        "sort_order": 1,
    },
    {
        "slug": "problem-solver",
        "name": "Problem Solver",
        "description": "10 ta masala — mustahkam start.",
        "category": Badge.Category.PROBLEM,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 10,
        "sort_order": 2,
    },
    {
        "slug": "rising-coder",
        "name": "Rising Coder",
        "description": "25 ta masala — ritm oshmoqda.",
        "category": Badge.Category.PROBLEM,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 25,
        "sort_order": 3,
    },
    {
        "slug": "challenge-hunter",
        "name": "Challenge Hunter",
        "description": "50 ta masala — haqiqiy ovchi.",
        "category": Badge.Category.PROBLEM,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 50,
        "sort_order": 4,
    },
    {
        "slug": "sql-explorer",
        "name": "SQL Explorer",
        "description": "Kamida 3 xil SQL mavzusidan masala yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.DISTINCT_SQL_TOPICS,
        "requirement_value": 3,
        "sort_order": 5,
    },
    {
        "slug": "join-master",
        "name": "JOIN Master",
        "description": "5 ta JOIN masalasini muvaffaqiyatli yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_JOIN},
        "sort_order": 6,
    },
    {
        "slug": "window-wizard",
        "name": "Window Wizard",
        "description": "5 ta Window Function masalasini yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_WINDOW},
        "sort_order": 7,
    },
    {
        "slug": "python-starter",
        "name": "Python Starter",
        "description": "5 ta Python masalasini yeching.",
        "category": Badge.Category.MASTERY,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": "python_any"},
        "sort_order": 8,
    },
    {
        "slug": "streak-3",
        "name": "3-Day Streak",
        "description": "3 kun ketma-ket o‘rganish faoliyati.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 3,
        "sort_order": 9,
    },
    {
        "slug": "streak-7",
        "name": "7-Day Streak",
        "description": "7 kunlik zanjir — odat shakllanmoqda.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 7,
        "sort_order": 10,
    },
    {
        "slug": "streak-30",
        "name": "30-Day Streak",
        "description": "30 kunlik zanjir — haqiqiy izchillik.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 30,
        "sort_order": 11,
    },
    {
        "slug": "first-lesson",
        "name": "First Lesson",
        "description": "Birinchi darsni tugatting.",
        "category": Badge.Category.LEARNING,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.LESSONS_COMPLETED,
        "requirement_value": 1,
        "sort_order": 12,
    },
    {
        "slug": "knowledge-seeker",
        "name": "Knowledge Seeker",
        "description": "10 ta darsni tugatting.",
        "category": Badge.Category.LEARNING,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.LESSONS_COMPLETED,
        "requirement_value": 10,
        "sort_order": 13,
    },
    {
        "slug": "course-finisher",
        "name": "Course Finisher",
        "description": "Butun bir nashr etilgan kursdagi barcha darslarni tugatting.",
        "category": Badge.Category.LEARNING,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.COURSE_COMPLETED,
        "requirement_value": 1,
        "sort_order": 14,
    },
    {
        "slug": "top-10",
        "name": "Top 10",
        "description": "Reytingda top-10 ga chiqing (tarixiy yutuq).",
        "category": Badge.Category.COMPETITION,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOP_RANK,
        "requirement_value": 10,
        "sort_order": 15,
    },
    {
        "slug": "top-3",
        "name": "Top 3",
        "description": "Reytingda top-3 ga chiqing.",
        "category": Badge.Category.COMPETITION,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.TOP_RANK,
        "requirement_value": 3,
        "sort_order": 16,
    },
    {
        "slug": "number-one",
        "name": "#1",
        "description": "Reytingda birinchi o‘ringa chiqing.",
        "category": Badge.Category.COMPETITION,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.TOP_RANK,
        "requirement_value": 1,
        "sort_order": 17,
    },
    {
        "slug": "perfect-week",
        "name": "Perfect Week",
        "description": "Bir haftaning 7 kunida ham o‘rganish faoliyati.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.PERFECT_WEEK,
        "requirement_value": 7,
        "sort_order": 18,
    },
    {
        "slug": "night-coder",
        "name": "Night Coder",
        "description": "Tungi o‘rganish soatlarida 10 ta faoliyat.",
        "category": Badge.Category.PLATFORM,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.NIGHT_ACTIVITY,
        "requirement_value": 10,
        "sort_order": 19,
    },
    # --- Data-driven expansion from pa_platform solve patterns ---
    {
        "slug": "century-coder",
        "name": "Century Coder",
        "description": "100 ta masala (skill-testlardan tashqari).",
        "category": Badge.Category.PROBLEM,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.PROBLEMS_SOLVED,
        "requirement_value": 100,
        "sort_order": 21,
    },
    {
        "slug": "easy-starter",
        "name": "Easy Starter",
        "description": "25 ta Easy darajadagi masala.",
        "category": Badge.Category.PROBLEM,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.DIFFICULTY_SOLVED,
        "requirement_value": 25,
        "requirement_meta": {"difficulty": "easy"},
        "sort_order": 22,
    },
    {
        "slug": "medium-solver",
        "name": "Medium Solver",
        "description": "15 ta Medium masala.",
        "category": Badge.Category.PROBLEM,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.DIFFICULTY_SOLVED,
        "requirement_value": 15,
        "requirement_meta": {"difficulty": "medium"},
        "sort_order": 23,
    },
    {
        "slug": "hard-crusher",
        "name": "Hard Crusher",
        "description": "3 ta Hard masala.",
        "category": Badge.Category.PROBLEM,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.DIFFICULTY_SOLVED,
        "requirement_value": 3,
        "requirement_meta": {"difficulty": "hard"},
        "sort_order": 24,
    },
    {
        "slug": "select-starter",
        "name": "SELECT Starter",
        "description": "5 ta SELECT/filtr masalasi (SQL asoslari + filtrlash).",
        "category": Badge.Category.MASTERY,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_SELECT},
        "sort_order": 25,
    },
    {
        "slug": "aggregation-master",
        "name": "Aggregation Master",
        "description": "5 ta GROUP BY / agregatsiya masalasi.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_GROUP},
        "sort_order": 26,
    },
    {
        "slug": "subquery-specialist",
        "name": "Subquery Specialist",
        "description": "5 ta subquery masalasi.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_SUBQUERY},
        "sort_order": 27,
    },
    {
        "slug": "cte-explorer",
        "name": "CTE Explorer",
        "description": "5 ta CTE masalasi.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_CTE},
        "sort_order": 28,
    },
    {
        "slug": "case-crafter",
        "name": "CASE Crafter",
        "description": "5 ta CASE masalasi.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.TOPIC_PROBLEMS,
        "requirement_value": 5,
        "requirement_meta": {"topic": TOPIC_CASE},
        "sort_order": 29,
    },
    {
        "slug": "sql-solver",
        "name": "SQL Solver",
        "description": "SQL kursida 25 ta masala (puzzle).",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.COURSE_SOLVES,
        "requirement_value": 25,
        "requirement_meta": {"course_slug": "sql", "include_skill_tests": False},
        "sort_order": 30,
    },
    {
        "slug": "sql-master",
        "name": "SQL Master",
        "description": "SQL kursida 50 ta masala.",
        "category": Badge.Category.MASTERY,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.COURSE_SOLVES,
        "requirement_value": 50,
        "requirement_meta": {"course_slug": "sql", "include_skill_tests": False},
        "sort_order": 31,
    },
    {
        "slug": "banking-starter",
        "name": "Banking English Starter",
        "description": "English for Banking da 10 ta to‘g‘ri javob (quiz/test).",
        "category": Badge.Category.LEARNING,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.COURSE_SOLVES,
        "requirement_value": 10,
        "requirement_meta": {"course_slug": "english-banking", "include_skill_tests": True},
        "sort_order": 32,
    },
    {
        "slug": "deven-starter",
        "name": "DevEnglish Starter",
        "description": "DevEnglish da 10 ta to‘g‘ri javob.",
        "category": Badge.Category.LEARNING,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.COURSE_SOLVES,
        "requirement_value": 10,
        "requirement_meta": {"course_slug": "english-it", "include_skill_tests": True},
        "sort_order": 33,
    },
    {
        "slug": "devru-starter",
        "name": "DevRussian Starter",
        "description": "DevRussian da 10 ta to‘g‘ri javob.",
        "category": Badge.Category.LEARNING,
        "rarity": "common",
        "requirement_type": Badge.RequirementType.COURSE_SOLVES,
        "requirement_value": 10,
        "requirement_meta": {"course_slug": "russian-it", "include_skill_tests": True},
        "sort_order": 34,
    },
    {
        "slug": "python-solver",
        "name": "Python Solver",
        "description": "Python kursida 15 ta mashq.",
        "category": Badge.Category.MASTERY,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.COURSE_SOLVES,
        "requirement_value": 15,
        "requirement_meta": {"course_slug": "python", "include_skill_tests": False},
        "sort_order": 35,
    },
    {
        "slug": "multi-skilled",
        "name": "Multi-Skilled",
        "description": "Kamida 2 ta kursda 5+ yechim.",
        "category": Badge.Category.PLATFORM,
        "rarity": "rare",
        "requirement_type": Badge.RequirementType.COURSES_ACTIVE,
        "requirement_value": 2,
        "requirement_meta": {"min_solves": 5, "include_skill_tests": True},
        "sort_order": 36,
    },
    {
        "slug": "polyglot-learner",
        "name": "Polyglot Learner",
        "description": "Kamida 3 ta kursda 5+ yechim.",
        "category": Badge.Category.PLATFORM,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.COURSES_ACTIVE,
        "requirement_value": 3,
        "requirement_meta": {"min_solves": 5, "include_skill_tests": True},
        "sort_order": 37,
    },
    {
        "slug": "streak-14",
        "name": "14-Day Streak",
        "description": "14 kunlik o‘rganish zanjiri.",
        "category": Badge.Category.CONSISTENCY,
        "rarity": "epic",
        "requirement_type": Badge.RequirementType.STREAK,
        "requirement_value": 14,
        "sort_order": 38,
    },
    {
        "slug": "legend",
        "name": "Legend",
        "description": "Boshqa badge lardan kamida 20 tasini yuting.",
        "category": Badge.Category.PLATFORM,
        "rarity": "legendary",
        "requirement_type": Badge.RequirementType.BADGES_EARNED,
        "requirement_value": 20,
        "requirement_meta": {"exclude_slugs": ["legend"]},
        "sort_order": 99,
    },
]


def ensure_badges() -> int:
    """Upsert badge definitions from catalog. Returns count of definitions."""
    for spec in BADGE_DEFINITIONS:
        Badge.objects.update_or_create(
            slug=spec["slug"],
            defaults={
                "name": spec["name"],
                "description": spec["description"],
                "category": spec["category"],
                "icon_path": f"badges/{spec['slug']}.svg",
                "rarity": spec.get("rarity") or "common",
                "requirement_type": spec["requirement_type"],
                "requirement_value": spec["requirement_value"],
                "requirement_meta": spec.get("requirement_meta") or {},
                "sort_order": spec["sort_order"],
                "is_active": True,
            },
        )
    return len(BADGE_DEFINITIONS)
