# Generated by Django 6.1 on 2026-08-27 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0005_engage_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Musobaqa',
                'verbose_name_plural': 'Musobaqalar',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0, help_text='0 bo‘lsa mashq qiyinligiga qarab hisoblanadi')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Musobaqa mashqi',
                'verbose_name_plural': 'Musobaqa mashqlari',
                'ordering': ['order', 'id'],
                'unique_together': {('contest', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='contests', through='contests.ContestExercise', to='exercises.exercise'),
        ),
        migrations.CreateModel(
            name='ContestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('last_solved_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contests.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musobaqa balli',
                'verbose_name_plural': 'Musobaqa ballari',
                'ordering': ['-points', 'last_solved_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('contest', 'student'), name='uniq_contest_student_score')],
            },
        ),
    ]
