# Generated by Django 5.1.8 on 2026-10-06 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('problem', 'Problem Solving'), ('consistency', 'Consistency'), ('learning', 'Learning'), ('competition', 'Competition'), ('mastery', 'Mastery'), ('platform', 'Platform')], db_index=True, max_length=20)),
                ('icon', models.CharField(default='🏅', max_length=16)),
                ('requirement_type', models.CharField(choices=[('problems_solved', 'Problems solved'), ('topic_problems', 'Topic problems'), ('distinct_sql_topics', 'Distinct SQL topics'), ('streak', 'Streak days'), ('lessons_completed', 'Lessons completed'), ('course_completed', 'Course completed'), ('top_rank', 'Best leaderboard rank'), ('perfect_week', 'Perfect calendar week'), ('night_activity', 'Night learning activities'), ('badges_earned', 'Other badges earned')], max_length=40)),
                ('requirement_value', models.PositiveIntegerField(default=1)),
                ('requirement_meta', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserRankPeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_rank', models.PositiveIntegerField()),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_peak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank peak',
                'verbose_name_plural': 'Rank peaks',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='badges.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User badge',
                'verbose_name_plural': 'User badges',
                'indexes': [models.Index(fields=['user', '-earned_at'], name='badges_user_user_id_022592_idx'), models.Index(fields=['badge'], name='badges_user_badge_i_014643_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge')],
            },
        ),
    ]
