# Generated by Django 5.1.8 on 2026-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_path',
            field=models.CharField(blank=True, help_text='Static path, e.g. badges/first-step.svg', max_length=255),
        ),
        migrations.AddField(
            model_name='badge',
            name='rarity',
            field=models.CharField(blank=True, default='common', help_text='common | rare | epic | legendary (visual weight)', max_length=20),
        ),
    ]
