# Generated by Django 5.1.8 on 2026-08-16 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('homework_submitted', 'Uy vazifasi yuborildi'), ('homework_reviewed', 'Uy vazifasi tekshirildi'), ('homework_revision', 'Qayta topshirish so‘raldi')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bildirishnoma hodisasi',
                'verbose_name_plural': 'Bildirishnoma hodisalari',
            },
        ),
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignment', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'Uy vazifasi',
                'verbose_name_plural': 'Uy vazifalari',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='homework/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Yuborilgan'), ('under_review', 'Ko‘rib chiqilmoqda'), ('reviewed', 'Tekshirilgan'), ('needs_revision', 'Qayta topshirish kerak')], default='submitted', max_length=30)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('additional_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('reviewed', 'Tekshirilgan'), ('needs_revision', 'Qayta topshirish kerak')], default='reviewed', max_length=30)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homework.homeworksubmission')),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['student', 'assignment', '-created_at'], name='homework_ho_student_0032fe_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['status'], name='homework_ho_status_189f4d_idx'),
        ),
    ]
