"""
Har bir SQL moduli uchun bilim testlari (kamida 10 ta, 4 variant).
Javoblar A/B/C/D — o‘qitilgan mavzuga mos, o‘zbekcha.
To‘g‘ri javob har savolda barqaror seed bilan aralashtiriladi (faqat A emas).
"""

from __future__ import annotations

import hashlib
import random
import re

_OPT_PREFIX = re.compile(r"^[A-D]\)\s*")
_EDITORIAL_LETTER = re.compile(r"^(To‘g‘ri javob:\s*)([A-D])(\.\s*)", re.S)


def _shuffle_quiz(num: int, title: str, options: list[str], answer: str, editorial: str) -> tuple[list[str], str, str]:
    """Stable shuffle so the correct letter is not always A."""
    bodies = [_OPT_PREFIX.sub("", item) for item in options]
    correct_text = bodies["ABCD".index(answer)]
    rng = random.Random(hashlib.md5(f"{num}|{title}".encode("utf-8")).hexdigest())
    order = list(range(4))
    rng.shuffle(order)
    shuffled = [bodies[i] for i in order]
    labeled = [f"{letter}) {text}" for letter, text in zip("ABCD", shuffled)]
    new_answer = "ABCD"[shuffled.index(correct_text)]
    new_editorial, n = _EDITORIAL_LETTER.subn(rf"\g<1>{new_answer}\g<3>", editorial, count=1)
    if n == 0:
        new_editorial = editorial
    return labeled, new_answer, new_editorial


def _q(num: int, title: str, task: str, options: list[str], answer: str, editorial: str, difficulty: str = "easy"):
    assert answer in "ABCD"
    assert len(options) == 4
    options, answer, editorial = _shuffle_quiz(num, title, options, answer, editorial)
    return {
        "num": num,
        "title": title,
        "description": "Modul bilim testi. To‘g‘ri javobni tanlang.",
        "task": task,
        "kind": "quiz",
        "difficulty": difficulty,
        "is_skill_test": True,
        "quiz_options": options,
        "hints": ["Darsdagi asosiy ta’rifni eslang.", "Noto‘g‘ri variantlarni chiqarib tashlang."],
        "editorial": editorial,
        "columns": ["javob"],
        "rows": [[answer]],
    }


MODULE_SKILL_TESTS: dict[str, list[dict]] = {
    "sql-asoslari": [
        _q(
            1,
            "SELECT nima qiladi?",
            "SELECT operatori asosan nima uchun ishlatiladi?",
            [
                "A) Jadvaldan ma’lumot o‘qish",
                "B) Jadvalni o‘chirish",
                "C) Yangi jadval yaratish",
                "D) Ustun nomini o‘zgartirish",
            ],
            "A",
            "To‘g‘ri javob: A. SELECT — ma’lumotni o‘qish (query) operatori.",
        ),
        _q(
            2,
            "FROM qismi",
            "FROM kalit so‘zi nimani bildiradi?",
            [
                "A) Qaysi jadvaldan o‘qish",
                "B) Natijani saralash",
                "C) Yangi qator qo‘shish",
                "D) Faqat ustun nomini berish",
            ],
            "A",
            "To‘g‘ri javob: A. FROM — ma’lumot qaysi jadvaldan olinishini ko‘rsatadi.",
        ),
        _q(
            3,
            "Ustun tanlash",
            "Faqat name ustunini olish uchun qaysi yozuv to‘g‘ri?",
            [
                "A) SELECT name FROM customers;",
                "B) GET name FROM customers;",
                "C) SHOW name TABLE customers;",
                "D) FIND name IN customers;",
            ],
            "A",
            "To‘g‘ri javob: A. Kerakli ustun SELECT dan keyin yoziladi.",
        ),
        _q(
            4,
            "Barcha ustunlar",
            "Jadvaldagi barcha ustunlarni olish uchun nima ishlatiladi?",
            [
                "A) SELECT * FROM jadval;",
                "B) SELECT ALL COLUMNS;",
                "C) SELECT EVERY FROM jadval;",
                "D) TAKE * FROM jadval;",
            ],
            "A",
            "To‘g‘ri javob: A. * — barcha ustunlar degani.",
        ),
        _q(
            5,
            "Natija qatori",
            "SELECT so‘rovi qaytaradigan natija nima deb ataladi?",
            [
                "A) Natija to‘plami (result set)",
                "B) Indeks",
                "C) Trigger",
                "D) Tranzaksiya jurnali",
            ],
            "A",
            "To‘g‘ri javob: A. SELECT natijasi — qatorlar to‘plami.",
        ),
        _q(
            6,
            "Kalit so‘z tartibi",
            "Oddiy SELECT so‘rovida to‘g‘ri tartib qaysi?",
            [
                "A) SELECT … FROM …;",
                "B) FROM … SELECT …;",
                "C) TABLE … SELECT …;",
                "D) FROM … WHERE … SELECT …;",
            ],
            "A",
            "To‘g‘ri javob: A. Avval SELECT, keyin FROM.",
        ),
        _q(
            7,
            "Bir nechta ustun",
            "name va city ustunlarini birga olish uchun nima qilinadi?",
            [
                "A) SELECT name, city FROM customers;",
                "B) SELECT name AND city FROM customers;",
                "C) SELECT name + city FROM customers;",
                "D) SELECT name WITH city FROM customers;",
            ],
            "A",
            "To‘g‘ri javob: A. Ustunlar vergul bilan ajratiladi.",
        ),
        _q(
            8,
            "Jadval nomi",
            "SQL da jadval nomi odatda qayerda yoziladi?",
            [
                "A) FROM dan keyin",
                "B) SELECT dan oldin",
                "C) Faqat WHERE ichida",
                "D) Faqat ORDER BY ichida",
            ],
            "A",
            "To‘g‘ri javob: A. Jadval FROM dan keyin ko‘rsatiladi.",
        ),
        _q(
            9,
            "O‘qish vs o‘zgartirish",
            "Qaysi operator jadvaldagi ma’lumotni o‘zgartirmaydi?",
            [
                "A) SELECT",
                "B) UPDATE",
                "C) DELETE",
                "D) INSERT",
            ],
            "A",
            "To‘g‘ri javob: A. SELECT faqat o‘qiydi, o‘zgartirmaydi.",
        ),
        _q(
            10,
            "Nuqta-vergul",
            "Ko‘p SQL muhitlarida so‘rov oxirida nima qo‘yiladi?",
            [
                "A) Nuqta-vergul (;)",
                "B) Ikki nuqta (:)",
                "C) Undov (!)",
                "D) So‘roq (?)",
            ],
            "A",
            "To‘g‘ri javob: A. So‘rov odatda ; bilan yakunlanadi.",
        ),
        _q(
            11,
            "Alias (AS)",
            "Ustun nomiga qisqa nom (alias) berish uchun qaysi kalit so‘z ishlatiladi?",
            [
                "A) AS",
                "B) IS",
                "C) TO",
                "D) NAME",
            ],
            "A",
            "To‘g‘ri javob: A. SELECT amount AS summa — alias beradi.",
            "medium",
        ),
    ],
    "filtrlash-va-saralash": [
        _q(
            1,
            "WHERE nima?",
            "WHERE operatori nima uchun kerak?",
            [
                "A) Qatorlarni shart bo‘yicha filtrlash",
                "B) Jadval yaratish",
                "C) Ustun qo‘shish",
                "D) Indeks o‘chirish",
            ],
            "A",
            "To‘g‘ri javob: A. WHERE — shartga mos qatorlarni qoldiradi.",
        ),
        _q(
            2,
            "Tenglik",
            "city = 'Toshkent' ifodasi nimani anglatadi?",
            [
                "A) Shahar Toshkentga teng",
                "B) Shahar Toshkentdan katta",
                "C) Shahar bo‘sh",
                "D) Shahar yo‘q",
            ],
            "A",
            "To‘g‘ri javob: A. = tenglik operatori.",
        ),
        _q(
            3,
            "ORDER BY",
            "ORDER BY nima qiladi?",
            [
                "A) Natijani saralaydi",
                "B) Jadvalni birlashtiradi",
                "C) Qator qo‘shadi",
                "D) Ustun o‘chiradi",
            ],
            "A",
            "To‘g‘ri javob: A. ORDER BY — tartiblash.",
        ),
        _q(
            4,
            "DESC",
            "ORDER BY amount DESC nimani bildiradi?",
            [
                "A) Summa kamayish tartibida",
                "B) Summa o‘sish tartibida",
                "C) Faqat NULL qatorlar",
                "D) Tasodifiy tartib",
            ],
            "A",
            "To‘g‘ri javob: A. DESC — kamayish (descending).",
        ),
        _q(
            5,
            "ASC",
            "ORDER BY name ASC — bu nima?",
            [
                "A) Ism o‘sish (A→Z) tartibida",
                "B) Ism kamayish tartibida",
                "C) Ism bo‘yicha guruhlash",
                "D) Ismni o‘chirish",
            ],
            "A",
            "To‘g‘ri javob: A. ASC — o‘sish tartibi (default).",
        ),
        _q(
            6,
            "AND",
            "WHERE city = 'Toshkent' AND amount > 1000 — bu qanday ishlaydi?",
            [
                "A) Ikkala shart ham bajarilishi kerak",
                "B) Faqat birinchi shart yetarli",
                "C) Faqat ikkinchi shart yetarli",
                "D) Hech qaysi shart kerak emas",
            ],
            "A",
            "To‘g‘ri javob: A. AND — barcha shartlar rost bo‘lishi shart.",
        ),
        _q(
            7,
            "OR",
            "OR operatori qachon rost?",
            [
                "A) Shartlardan kamida bittasi rost bo‘lsa",
                "B) Faqat hammasi rost bo‘lsa",
                "C) Hech biri rost bo‘lmasa",
                "D) Faqat NULL bo‘lsa",
            ],
            "A",
            "To‘g‘ri javob: A. OR — kamida bitta rost shart yetadi.",
        ),
        _q(
            8,
            "Taqqoslash",
            "amount >= 50000 ifodasi nimani anglatadi?",
            [
                "A) Summa 50000 yoki undan katta",
                "B) Summa faqat 50000",
                "C) Summa 50000 dan kichik",
                "D) Summa NULL",
            ],
            "A",
            "To‘g‘ri javob: A. >= — katta yoki teng.",
        ),
        _q(
            9,
            "WHERE joylashuvi",
            "WHERE odatda qayerda yoziladi?",
            [
                "A) FROM dan keyin, ORDER BY dan oldin",
                "B) SELECT dan oldin",
                "C) ORDER BY dan keyin",
                "D) Faqat so‘rov oxirida",
            ],
            "A",
            "To‘g‘ri javob: A. Tartib: SELECT → FROM → WHERE → ORDER BY.",
        ),
        _q(
            10,
            "Matn qiymat",
            "SQL da matn qiymat odatda qanday yoziladi?",
            [
                "A) Bir tirnoq ichida: 'Toshkent'",
                "B) Qavs ichida: (Toshkent)",
                "C) Qavsiz: Toshkent",
                "D) Kvadrat qavs: [Toshkent]",
            ],
            "A",
            "To‘g‘ri javob: A. Matnlar odatda '...' ichida.",
        ),
        _q(
            11,
            "LIKE",
            "LIKE operatori nima uchun ishlatiladi?",
            [
                "A) Matn shabloniga moslash (masalan, 'A%')",
                "B) Jadval yaratish",
                "C) Indeks o‘chirish",
                "D) Faqat sana solishtirish",
            ],
            "A",
            "To‘g‘ri javob: A. LIKE — matn pattern filtri.",
            "medium",
        ),
    ],
    "agregatsiyalar": [
        _q(
            1,
            "COUNT",
            "COUNT(*) nima qiladi?",
            [
                "A) Qatorlar sonini sanaydi",
                "B) Summani hisoblaydi",
                "C) O‘rtachani topadi",
                "D) Eng katta qiymatni oladi",
            ],
            "A",
            "To‘g‘ri javob: A. COUNT(*) — qatorlar soni.",
        ),
        _q(
            2,
            "SUM",
            "SUM(amount) nimani beradi?",
            [
                "A) amount ustuni yig‘indisini",
                "B) amount o‘rtachasini",
                "C) amount eng kichigini",
                "D) amount ustun nomini",
            ],
            "A",
            "To‘g‘ri javob: A. SUM — yig‘indi.",
        ),
        _q(
            3,
            "AVG",
            "AVG(amount) nima?",
            [
                "A) O‘rtacha qiymat",
                "B) Eng katta qiymat",
                "C) Eng kichik qiymat",
                "D) Qatorlar soni",
            ],
            "A",
            "To‘g‘ri javob: A. AVG — average (o‘rtacha).",
        ),
        _q(
            4,
            "MAX / MIN",
            "MAX(amount) nima qaytaradi?",
            [
                "A) Eng katta summa",
                "B) Eng kichik summa",
                "C) O‘rtacha summa",
                "D) Yig‘indi",
            ],
            "A",
            "To‘g‘ri javob: A. MAX — maksimum.",
        ),
        _q(
            5,
            "GROUP BY",
            "GROUP BY nima uchun kerak?",
            [
                "A) Qatorlarni guruhlab agregat hisoblash",
                "B) Faqat saralash",
                "C) Jadval yaratish",
                "D) Indeks qo‘yish",
            ],
            "A",
            "To‘g‘ri javob: A. GROUP BY — guruhlash.",
        ),
        _q(
            6,
            "Guruh + COUNT",
            "Har shahar bo‘yicha mijozlar soni uchun qaysi yondashuv to‘g‘ri?",
            [
                "A) GROUP BY city + COUNT(*)",
                "B) Faqat ORDER BY city",
                "C) Faqat WHERE city",
                "D) Faqat SELECT city",
            ],
            "A",
            "To‘g‘ri javob: A. Guruhlab sanash — GROUP BY + COUNT.",
        ),
        _q(
            7,
            "Agregat qayerda",
            "COUNT, SUM kabi funksiyalar odatda qayerda yoziladi?",
            [
                "A) SELECT ro‘yxatida",
                "B) FROM dan oldin",
                "C) Faqat ORDER BY ichida",
                "D) Faqat jadval nomida",
            ],
            "A",
            "To‘g‘ri javob: A. Agregatlar SELECT da hisoblanadi.",
        ),
        _q(
            8,
            "GROUP BY qoidasi",
            "GROUP BY ishlatganda SELECT dagi oddiy ustunlar haqida nima to‘g‘ri?",
            [
                "A) Ular GROUP BY da ham bo‘lishi kerak (odatda)",
                "B) Ular hech qachon yozilmaydi",
                "C) Faqat * yoziladi",
                "D) Faqat WHERE da bo‘ladi",
            ],
            "A",
            "To‘g‘ri javob: A. Guruhlanmagan ustunni SELECT da erkin yozib bo‘lmaydi.",
            "medium",
        ),
        _q(
            9,
            "DISTINCT",
            "COUNT(DISTINCT city) nimani beradi?",
            [
                "A) Takrorlanmas shaharlar soni",
                "B) Barcha qatorlar soni",
                "C) Eng uzun shahar nomi",
                "D) Shaharlar yig‘indisi",
            ],
            "A",
            "To‘g‘ri javob: A. DISTINCT — unikal qiymatlar.",
            "medium",
        ),
        _q(
            10,
            "Filtr vs agregat",
            "Qatorlarni agregatdan oldin filtrlash uchun nima ishlatiladi?",
            [
                "A) WHERE",
                "B) HAVING",
                "C) LIMIT",
                "D) UNION",
            ],
            "A",
            "To‘g‘ri javob: A. WHERE — guruhlashdan oldin filtr.",
        ),
        _q(
            11,
            "Yig‘indi misoli",
            "Barcha tranzaksiyalar jami summasi uchun eng to‘g‘ri yondashuv?",
            [
                "A) SELECT SUM(amount) FROM transactions;",
                "B) SELECT amount FROM transactions;",
                "C) SELECT COUNT(amount) FROM transactions;",
                "D) SELECT MAX(*) FROM transactions;",
            ],
            "A",
            "To‘g‘ri javob: A. Jami summa — SUM(amount).",
        ),
    ],
    "group-by-having": [
        _q(
            1,
            "HAVING nima?",
            "HAVING nima uchun ishlatiladi?",
            [
                "A) Guruhlangan natijani filtrlash",
                "B) Jadval yaratish",
                "C) Ustun qo‘shish",
                "D) Faqat saralash",
            ],
            "A",
            "To‘g‘ri javob: A. HAVING — GROUP BY dan keyin filtr.",
        ),
        _q(
            2,
            "WHERE vs HAVING",
            "Qaysi gap to‘g‘ri?",
            [
                "A) WHERE — qatorlar, HAVING — guruhlar uchun",
                "B) HAVING — qatorlar, WHERE — guruhlar uchun",
                "C) Ikkalasi bir xil",
                "D) HAVING faqat SELECT dan oldin",
            ],
            "A",
            "To‘g‘ri javob: A. WHERE qatorni, HAVING guruhni filtrlaydi.",
        ),
        _q(
            3,
            "COUNT + HAVING",
            "Kamida 2 mijozli shaharlarni topish uchun nima kerak?",
            [
                "A) GROUP BY city HAVING COUNT(*) >= 2",
                "B) WHERE COUNT(*) >= 2",
                "C) ORDER BY COUNT(*)",
                "D) SELECT city WHERE 2",
            ],
            "A",
            "To‘g‘ri javob: A. Avval guruhla, keyin HAVING bilan filtrla.",
        ),
        _q(
            4,
            "Ko‘p ustunli GROUP BY",
            "GROUP BY city, transaction_type nimani anglatadi?",
            [
                "A) Shahar va tur juftligi bo‘yicha guruhlash",
                "B) Faqat shahar bo‘yicha guruhlash",
                "C) Faqat tur bo‘yicha guruhlash",
                "D) Guruhlash yo‘q",
            ],
            "A",
            "To‘g‘ri javob: A. Bir nechta ustun bo‘yicha guruhlash mumkin.",
        ),
        _q(
            5,
            "HAVING joyi",
            "HAVING odatda qayerda turadi?",
            [
                "A) GROUP BY dan keyin",
                "B) FROM dan oldin",
                "C) SELECT dan oldin",
                "D) WHERE dan oldin",
            ],
            "A",
            "To‘g‘ri javob: A. Tartib: GROUP BY → HAVING → ORDER BY.",
        ),
        _q(
            6,
            "Agregat HAVING da",
            "HAVING COUNT(*) > 5 — bu qonuniymi?",
            [
                "A) Ha, HAVING da agregat bo‘lishi mumkin",
                "B) Yo‘q, faqat WHERE da mumkin",
                "C) Yo‘q, hech qachon",
                "D) Faqat LIMIT da",
            ],
            "A",
            "To‘g‘ri javob: A. HAVING agregat shartlari uchun yaratilgan.",
        ),
        _q(
            7,
            "Noto‘g‘ri WHERE",
            "Nima uchun WHERE COUNT(*) > 2 odatda ishlamaydi?",
            [
                "A) COUNT guruhlashdan keyin hisoblanadi",
                "B) COUNT degan operator yo‘q",
                "C) WHERE umuman ishlamaydi",
                "D) * belgisini yozib bo‘lmaydi",
            ],
            "A",
            "To‘g‘ri javob: A. Agregat filtri uchun HAVING kerak.",
            "medium",
        ),
        _q(
            8,
            "Guruh natijasi",
            "GROUP BY dan keyin har bir guruh uchun nechta qator chiqadi?",
            [
                "A) Odatda bitta (agregatlar bilan)",
                "B) Doim 10 ta",
                "C) Doim 0 ta",
                "D) Jadvaldagi barcha qatorlar",
            ],
            "A",
            "To‘g‘ri javob: A. Har guruh — odatda bitta yig‘ma qator.",
        ),
        _q(
            9,
            "Filtrlash tartibi",
            "Avval qatorlarni, keyin guruhlarni filtrlash tartibi?",
            [
                "A) WHERE → GROUP BY → HAVING",
                "B) HAVING → GROUP BY → WHERE",
                "C) GROUP BY → WHERE → HAVING",
                "D) ORDER BY → WHERE → HAVING",
            ],
            "A",
            "To‘g‘ri javob: A. Avval WHERE, keyin guruh, keyin HAVING.",
            "medium",
        ),
        _q(
            10,
            "Amaliy maqsad",
            "«Kamida 5 talabali sinflar» tipidagi masala uchun asosiy vosita?",
            [
                "A) GROUP BY + HAVING",
                "B) Faqat ORDER BY",
                "C) Faqat LIMIT",
                "D) Faqat DISTINCT",
            ],
            "A",
            "To‘g‘ri javob: A. Sanoq + chegaradan katta guruhlar — HAVING.",
        ),
        _q(
            11,
            "SUM + HAVING",
            "Yig‘indisi 100000 dan katta mijozlarni topish uchun?",
            [
                "A) GROUP BY customer_id HAVING SUM(amount) > 100000",
                "B) WHERE SUM(amount) > 100000",
                "C) ORDER BY SUM(amount)",
                "D) SELECT SUM WHERE 100000",
            ],
            "A",
            "To‘g‘ri javob: A. Guruh yig‘indisini HAVING bilan filtrlang.",
            "medium",
        ),
    ],
    "joins": [
        _q(
            1,
            "JOIN nima?",
            "JOIN nima uchun ishlatiladi?",
            [
                "A) Ikki (yoki undan ortiq) jadvalni bog‘lash",
                "B) Faqat bitta jadvalni o‘chirish",
                "C) Indeks yaratish",
                "D) Backup olish",
            ],
            "A",
            "To‘g‘ri javob: A. JOIN — jadvallarni bog‘laydi.",
        ),
        _q(
            2,
            "INNER JOIN",
            "INNER JOIN qanday qatorlarni qoldiradi?",
            [
                "A) Ikkala jadvalda mos kelganlarini",
                "B) Faqat chap jadvaldagi barchasini",
                "C) Faqat o‘ng jadvaldagi barchasini",
                "D) Hech qaysisini",
            ],
            "A",
            "To‘g‘ri javob: A. INNER JOIN — kesishma (match).",
        ),
        _q(
            3,
            "LEFT JOIN",
            "LEFT JOIN da chap jadval haqida nima to‘g‘ri?",
            [
                "A) Chap jadvaldagi barcha qatorlar saqlanadi",
                "B) Chap jadval umuman chiqmaydi",
                "C) Faqat mos kelganlari chiqadi",
                "D) Faqat o‘ng jadval chiqadi",
            ],
            "A",
            "To‘g‘ri javob: A. LEFT JOIN chapni to‘liq saqlaydi.",
        ),
        _q(
            4,
            "ON sharti",
            "ON c.id = t.customer_id nima?",
            [
                "A) Bog‘lanish sharti (kalitlar tengligi)",
                "B) Saralash sharti",
                "C) Jadval yaratish",
                "D) Ustun o‘chirish",
            ],
            "A",
            "To‘g‘ri javob: A. ON — qaysi ustunlar orqali bog‘lash.",
        ),
        _q(
            5,
            "NULL LEFT JOIN da",
            "LEFT JOIN da o‘ng jadvalda mos qator bo‘lmasa nima bo‘ladi?",
            [
                "A) O‘ng tomon ustunlari NULL bo‘lishi mumkin",
                "B) So‘rov xato beradi",
                "C) Chap qator yo‘qoladi",
                "D) Avtomatik DELETE bo‘ladi",
            ],
            "A",
            "To‘g‘ri javob: A. Mos kelmasa — NULL.",
        ),
        _q(
            6,
            "Tranzaksiyasiz mijoz",
            "Tranzaksiyasi yo‘q mijozlarni topish uchun tipik usul?",
            [
                "A) LEFT JOIN + WHERE o‘ng.id IS NULL",
                "B) INNER JOIN + WHERE id = 0",
                "C) ORDER BY NULL",
                "D) SELECT * WITHOUT JOIN",
            ],
            "A",
            "To‘g‘ri javob: A. «Yo‘q»ni topish — LEFT JOIN + IS NULL.",
            "medium",
        ),
        _q(
            7,
            "Alias jadvalda",
            "FROM customers AS c — bu nima?",
            [
                "A) Jadvalga qisqa nom (alias)",
                "B) Yangi jadval yaratish",
                "C) Indeks nomi",
                "D) View o‘chirish",
            ],
            "A",
            "To‘g‘ri javob: A. AS c — qisqa nom.",
        ),
        _q(
            8,
            "Qaysi JOIN «faqat mos»?",
            "Faqat ikkala tomonda bor qatorlar kerak bo‘lsa?",
            [
                "A) INNER JOIN",
                "B) LEFT JOIN",
                "C) RIGHT JOIN doim",
                "D) CROSS JOIN doim",
            ],
            "A",
            "To‘g‘ri javob: A. Moslar — INNER JOIN.",
        ),
        _q(
            9,
            "Ko‘p qator",
            "Bir mijozning 3 ta tranzaksiyasi bo‘lsa INNER JOIN natijasi?",
            [
                "A) Odatda 3 qator (har tranzaksiya uchun)",
                "B) Doim 1 qator",
                "C) Doim 0 qator",
                "D) Xato chiqadi",
            ],
            "A",
            "To‘g‘ri javob: A. Har mos juftlik — alohida qator.",
            "medium",
        ),
        _q(
            10,
            "SELECT da ustun",
            "JOIN qilganda ustunni aniq yozish nima uchun yaxshi?",
            [
                "A) Nomlar chalkashmasin (jadval.ustun)",
                "B) JOIN ishlamasin",
                "C) WHERE o‘chsin",
                "D) ORDER BY taqiqlansin",
            ],
            "A",
            "To‘g‘ri javob: A. Ambiguous column xatosidan saqlaydi.",
        ),
        _q(
            11,
            "Amaliy bog‘lanish",
            "customers va transactions odatda qanday bog‘lanadi?",
            [
                "A) customers.id = transactions.customer_id",
                "B) customers.name = transactions.amount",
                "C) customers.city = transactions.id",
                "D) Bog‘lanish shart emas",
            ],
            "A",
            "To‘g‘ri javob: A. Tashqi kalit customer_id orqali.",
        ),
    ],
    "subqueries": [
        _q(
            1,
            "Subquery nima?",
            "Subquery (ichki so‘rov) nima?",
            [
                "A) Boshqa so‘rov ichidagi so‘rov",
                "B) Yangi jadval turi",
                "C) Indeks nomi",
                "D) Backup fayli",
            ],
            "A",
            "To‘g‘ri javob: A. Ichki SELECT — subquery.",
        ),
        _q(
            2,
            "WHERE subquery",
            "WHERE amount > (SELECT AVG(amount) ...) nima qiladi?",
            [
                "A) O‘rtachadan katta summarni filtrlaydi",
                "B) Barcha qatorlarni o‘chiradi",
                "C) Jadval yaratadi",
                "D) Faqat saralaydi",
            ],
            "A",
            "To‘g‘ri javob: A. Ichki AVG bilan solishtirish.",
        ),
        _q(
            3,
            "IN",
            "city IN ('Toshkent', 'Samarqand') nimani anglatadi?",
            [
                "A) Shahar ro‘yxatdagi qiymatlardan biri",
                "B) Shahar ikkalasiga ham teng",
                "C) Shahar bo‘sh",
                "D) Shahar NULL",
            ],
            "A",
            "To‘g‘ri javob: A. IN — ro‘yxatda borligini tekshiradi.",
        ),
        _q(
            4,
            "FROM subquery",
            "FROM (SELECT ...) AS t — bu nima?",
            [
                "A) Ichki natijani vaqtinchalik jadval sifatida ishlatish",
                "B) View o‘chirish",
                "C) Indeks yaratish",
                "D) Transaction boshlash",
            ],
            "A",
            "To‘g‘ri javob: A. Derived table / subquery in FROM.",
            "medium",
        ),
        _q(
            5,
            "EXISTS",
            "EXISTS (subquery) odatda nima uchun?",
            [
                "A) Ichki so‘rovda kamida 1 qator bor-yo‘qligini tekshirish",
                "B) Jadval nomini o‘zgartirish",
                "C) Ustun tipini o‘zgartirish",
                "D) Backup",
            ],
            "A",
            "To‘g‘ri javob: A. EXISTS — mavjudlik tekshiruvi.",
            "medium",
        ),
        _q(
            6,
            "Qavs",
            "Subquery odatda qanday yoziladi?",
            [
                "A) Qavs ichida: (SELECT ...)",
                "B) Faqat {} ichida",
                "C) Faqat [] ichida",
                "D) Qavssiz yozib bo‘lmaydi",
            ],
            "A",
            "To‘g‘ri javob: A. Subquery odatda ( ) ichida.",
        ),
        _q(
            7,
            "Skalyar subquery",
            "WHERE da bitta qiymat qaytaradigan subquery nima deb ataladi?",
            [
                "A) Scalar subquery",
                "B) Cross join",
                "C) Window",
                "D) Trigger",
            ],
            "A",
            "To‘g‘ri javob: A. Bitta qiymat — scalar.",
            "medium",
        ),
        _q(
            8,
            "Noto‘g‘ri solishtirish",
            "Agar subquery ko‘p qator qaytarsa va siz = bilan solishtirsangiz?",
            [
                "A) Xato chiqishi mumkin (bir qiymat kutadi)",
                "B) Doim to‘g‘ri ishlaydi",
                "C) Avtomatik IN ga aylanadi",
                "D) Jadval o‘chadi",
            ],
            "A",
            "To‘g‘ri javob: A. Ko‘p qator uchun IN/EXISTS kerak.",
            "medium",
        ),
        _q(
            9,
            "Amaliy foyda",
            "Subqueryning asosiy foydasi?",
            [
                "A) Bosqichma-bosqich hisoblash / solishtirish",
                "B) Diskni tozalash",
                "C) Parolni saqlash",
                "D) UI chizish",
            ],
            "A",
            "To‘g‘ri javob: A. Ichki natijadan foydalanib tashqi so‘rov yoziladi.",
        ),
        _q(
            10,
            "NOT IN",
            "id NOT IN (SELECT ...) taxminan nimani bildiradi?",
            [
                "A) Ichki ro‘yxatda yo‘q id lar",
                "B) Faqat ichki ro‘yxatdagi id lar",
                "C) Barcha id lar",
                "D) Faqat NULL id lar",
            ],
            "A",
            "To‘g‘ri javob: A. NOT IN — ro‘yxatdan tashqarida.",
        ),
        _q(
            11,
            "O‘rtacha bilan filtr",
            "O‘rtachadan qimmat to‘lovlar uchun eng to‘g‘ri yondashuv?",
            [
                "A) WHERE amount > (SELECT AVG(amount) FROM ...)",
                "B) WHERE AVG(amount) > amount",
                "C) ORDER BY AVG(amount)",
                "D) GROUP BY AVG(amount)",
            ],
            "A",
            "To‘g‘ri javob: A. AVG ni ichki so‘rovda hisoblang.",
        ),
    ],
    "ctes": [
        _q(
            1,
            "CTE nima?",
            "CTE (WITH ...) nima?",
            [
                "A) Nomlangan vaqtinchalik natija to‘plami",
                "B) Doimiy yangi jadval",
                "C) Indeks turi",
                "D) Foydalanuvchi roli",
            ],
            "A",
            "To‘g‘ri javob: A. CTE — Common Table Expression.",
        ),
        _q(
            2,
            "WITH sintaksisi",
            "CTE qaysi kalit so‘z bilan boshlanadi?",
            [
                "A) WITH",
                "B) CREATE",
                "C) ALTER",
                "D) DROP",
            ],
            "A",
            "To‘g‘ri javob: A. WITH nom AS (SELECT ...).",
        ),
        _q(
            3,
            "CTE foydasi",
            "CTE ning asosiy afzalligi?",
            [
                "A) So‘rovni bosqichlarga bo‘lib o‘qish osonlashadi",
                "B) Diskni formatlaydi",
                "C) Parolni yashiradi",
                "D) Brauzer ochadi",
            ],
            "A",
            "To‘g‘ri javob: A. O‘qilishi oson, qayta ishlatish qulay.",
        ),
        _q(
            4,
            "CTE dan keyin",
            "WITH ... AS (...) dan keyin nima bo‘ladi?",
            [
                "A) Asosiy SELECT (yoki boshqa so‘rov)",
                "B) Majburiy DROP TABLE",
                "C) Majburiy CREATE INDEX",
                "D) Hech narsa yozilmaydi",
            ],
            "A",
            "To‘g‘ri javob: A. CTE dan keyin asosiy so‘rov yoziladi.",
        ),
        _q(
            5,
            "Bir nechta CTE",
            "Bir so‘rovda bir nechta CTE bo‘lishi mumkinmi?",
            [
                "A) Ha, vergul bilan ajratib",
                "B) Yo‘q, faqat bittasi",
                "C) Faqat 100 tadan keyin",
                "D) Faqat DELETE da",
            ],
            "A",
            "To‘g‘ri javob: A. WITH a AS (...), b AS (...) SELECT ...",
            "medium",
        ),
        _q(
            6,
            "CTE vs subquery",
            "CTE ni subquery o‘rniga ishlatishning sababi?",
            [
                "A) Nom berib, murakkab mantiqni soddalashtirish",
                "B) SELECT ni taqiqlash",
                "C) WHERE ni o‘chirish",
                "D) JOIN ni taqiqlash",
            ],
            "A",
            "To‘g‘ri javob: A. O‘qilishi va qayta foydalanish.",
        ),
        _q(
            7,
            "Debit CTE",
            "Avval debitlarni ajratib, keyin SUM olish — qaysi yondashuv?",
            [
                "A) WITH debitlar AS (SELECT ... WHERE type='debit') SELECT SUM...",
                "B) DROP debitlar;",
                "C) CREATE USER debitlar;",
                "D) GRANT debitlar;",
            ],
            "A",
            "To‘g‘ri javob: A. Avval filtr CTE, keyin agregat.",
        ),
        _q(
            8,
            "CTE umri",
            "Oddiy CTE qachon «yashaydi»?",
            [
                "A) Asosan shu so‘rov bajarilishicha",
                "B) Doimiy, abadiy",
                "C) Faqat 1 soniya",
                "D) Faqat server o‘chmaguncha",
            ],
            "A",
            "To‘g‘ri javob: A. CTE — so‘rov doirasida.",
            "medium",
        ),
        _q(
            9,
            "AS (SELECT)",
            "WITH x AS (SELECT ...) da qavs ichida nima turadi?",
            [
                "A) SELECT so‘rovi",
                "B) Faqat jadval nomi",
                "C) Faqat parol",
                "D) Faqat IP manzil",
            ],
            "A",
            "To‘g‘ri javob: A. CTE tanasi — SELECT.",
        ),
        _q(
            10,
            "CTE dan foydalanish",
            "CTE natijasiga qanday murojaat qilinadi?",
            [
                "A) Uning nomi bilan (FROM x yoki SELECT ... FROM x)",
                "B) Faqat * belgis bilan",
                "C) Faqat raqam bilan",
                "D) Murojaat qilib bo‘lmaydi",
            ],
            "A",
            "To‘g‘ri javob: A. CTE nomi — vaqtinchalik jadval nomi.",
        ),
        _q(
            11,
            "Amaliy",
            "3+ tranzaksiyali mijozlarni CTE bilan topishda odatda nima bo‘ladi?",
            [
                "A) CTE da COUNT, tashqarida filtr",
                "B) CTE da DROP",
                "C) CTE da CREATE USER",
                "D) CTE da GRANT",
            ],
            "A",
            "To‘g‘ri javob: A. Avval sanoq, keyin shart.",
            "medium",
        ),
    ],
    "case": [
        _q(
            1,
            "CASE nima?",
            "CASE WHEN nima uchun kerak?",
            [
                "A) Shartga qarab qiymat tanlash",
                "B) Jadval o‘chirish",
                "C) Foydalanuvchi yaratish",
                "D) Backup",
            ],
            "A",
            "To‘g‘ri javob: A. CASE — shartli ifoda.",
        ),
        _q(
            2,
            "WHEN / THEN",
            "CASE WHEN amount >= 50000 THEN 'katta' — bu nima?",
            [
                "A) Shart bajarilsa 'katta' qaytaradi",
                "B) Jadvalni o‘chiradi",
                "C) Ustun qo‘shadi",
                "D) Indeks yaratadi",
            ],
            "A",
            "To‘g‘ri javob: A. WHEN shart, THEN natija.",
        ),
        _q(
            3,
            "ELSE",
            "ELSE qismi nima uchun?",
            [
                "A) Hech qaysi WHEN mos kelmasa",
                "B) Faqat xato chiqarish",
                "C) Faqat JOIN uchun",
                "D) Majburiy emas va ishlamaydi",
            ],
            "A",
            "To‘g‘ri javob: A. ELSE — default qiymat.",
        ),
        _q(
            4,
            "END",
            "CASE ifodasi nima bilan yakunlanadi?",
            [
                "A) END",
                "B) STOP",
                "C) FINISH",
                "D) CLOSE",
            ],
            "A",
            "To‘g‘ri javob: A. CASE ... END.",
        ),
        _q(
            5,
            "SELECT da CASE",
            "CASE ni SELECT da ishlatish mumkinmi?",
            [
                "A) Ha, yangi ustun sifatida",
                "B) Yo‘q, hech qachon",
                "C) Faqat FROM da",
                "D) Faqat DROP da",
            ],
            "A",
            "To‘g‘ri javob: A. SELECT da yorliq/ustun yasash uchun.",
        ),
        _q(
            6,
            "Birinchi mos",
            "Bir nechta WHEN bo‘lsa qaysi ishlaydi?",
            [
                "A) Birinchi rost (mos) WHEN",
                "B) Oxirgi WHEN doim",
                "C) Tasodifiy WHEN",
                "D) Hammasi birga",
            ],
            "A",
            "To‘g‘ri javob: A. Yuqoridan pastga — birinchi mos.",
            "medium",
        ),
        _q(
            7,
            "CASE + agregat",
            "SUM(CASE WHEN ... THEN 1 ELSE 0 END) nima beradi?",
            [
                "A) Shartga mos qatorlar soniga yaqin hisob",
                "B) Jadval nomini",
                "C) Parolni",
                "D) IP manzilni",
            ],
            "A",
            "To‘g‘ri javob: A. Shartli sanash usuli.",
            "medium",
        ),
        _q(
            8,
            "Katta/kichik",
            "amount ga 'katta'/'kichik' yorlig‘i uchun asosiy vosita?",
            [
                "A) CASE WHEN",
                "B) DROP TABLE",
                "C) CREATE USER",
                "D) GRANT ALL",
            ],
            "A",
            "To‘g‘ri javob: A. Yorliq — CASE bilan.",
        ),
        _q(
            9,
            "NULL CASE da",
            "Hech qaysi WHEN mos kelmasa va ELSE yo‘q bo‘lsa?",
            [
                "A) Natija NULL bo‘lishi mumkin",
                "B) Server o‘chadi",
                "C) Doim 0",
                "D) Doim 'error'",
            ],
            "A",
            "To‘g‘ri javob: A. ELSE bo‘lmasa — NULL.",
            "medium",
        ),
        _q(
            10,
            "Alias bilan",
            "CASE ... END AS label — bu nima?",
            [
                "A) Natija ustuniga nom berish",
                "B) Jadval o‘chirish",
                "C) Indeks yaratish",
                "D) View drop",
            ],
            "A",
            "To‘g‘ri javob: A. AS — ustun alias.",
        ),
        _q(
            11,
            "Qayerda emas",
            "CASE ni qayerda ishlatish odatda ma’nosiz?",
            [
                "A) DROP TABLE o‘rniga",
                "B) SELECT da",
                "C) ORDER BY da (ba’zan)",
                "D) Aggregatsiya ichida",
            ],
            "A",
            "To‘g‘ri javob: A. CASE — ifoda, DDL o‘rnini bosmaydi.",
        ),
    ],
    "date-time": [
        _q(
            1,
            "Sana filtri",
            "Muayyan sanani filtrlash uchun odatda nima ishlatiladi?",
            [
                "A) WHERE transaction_date = '2024-03-01'",
                "B) WHERE date DROP",
                "C) WHERE CREATE date",
                "D) WHERE USER date",
            ],
            "A",
            "To‘g‘ri javob: A. Sana qiymati bilan WHERE.",
        ),
        _q(
            2,
            "Sana formati",
            "SQL da sana odatda qanday yoziladi?",
            [
                "A) 'YYYY-MM-DD' ko‘rinishida",
                "B) 'DD/YYYY/MM' majburiy",
                "C) Faqat son: 20240301 har doim",
                "D) Matnsiz",
            ],
            "A",
            "To‘g‘ri javob: A. ISO ko‘rinish keng tarqalgan.",
        ),
        _q(
            3,
            "Sana bo‘yicha GROUP BY",
            "Kunlik tranzaksiyalar soni uchun nima qilinadi?",
            [
                "A) GROUP BY transaction_date + COUNT(*)",
                "B) DROP BY date",
                "C) CREATE BY date",
                "D) USER BY date",
            ],
            "A",
            "To‘g‘ri javob: A. Kun bo‘yicha guruhlab sanash.",
        ),
        _q(
            4,
            "Oraliq",
            "Ikki sana orasidagi qatorlar uchun tipik operator?",
            [
                "A) BETWEEN yoki >= va <=",
                "B) DROP BETWEEN",
                "C) CREATE BETWEEN",
                "D) USER BETWEEN",
            ],
            "A",
            "To‘g‘ri javob: A. Oraliq — BETWEEN / solishtirish.",
        ),
        _q(
            5,
            "Kunlik ko‘rsatkich",
            "Har kun va tur bo‘yicha son — qanday guruhlash?",
            [
                "A) GROUP BY transaction_date, transaction_type",
                "B) GROUP BY faqat amount",
                "C) GROUP BY yo‘q",
                "D) GROUP BY SELECT",
            ],
            "A",
            "To‘g‘ri javob: A. Ikki o‘lchov bo‘yicha guruhlash.",
            "medium",
        ),
        _q(
            6,
            "Mart oyi",
            "2024-yil martidagi yozuvlarni olish uchun mantiqiy yondashuv?",
            [
                "A) Sana oralig‘ini filtrlash (oy boshidan oxirigacha)",
                "B) WHERE month = DROP",
                "C) WHERE year CREATE",
                "D) WHERE day USER",
            ],
            "A",
            "To‘g‘ri javob: A. Oy oralig‘ini WHERE bilan bering.",
        ),
        _q(
            7,
            "Sana ustuni tipi",
            "Sana ustunida matn bilan solishtirishda nima muhim?",
            [
                "A) Format mosligi",
                "B) Faqat rang",
                "C) Faqat shrift",
                "D) Faqat brauzer",
            ],
            "A",
            "To‘g‘ri javob: A. Format mos bo‘lishi kerak.",
            "medium",
        ),
        _q(
            8,
            "ORDER BY sana",
            "Eng yangi yozuvlar tepada bo‘lishi uchun?",
            [
                "A) ORDER BY transaction_date DESC",
                "B) ORDER BY transaction_date ASC doim yangi",
                "C) ORDER BY name",
                "D) ORDER BY yo‘q",
            ],
            "A",
            "To‘g‘ri javob: A. Yangidan eskiga — DESC.",
        ),
        _q(
            9,
            "COUNT + sana",
            "Muayyan kundagi operatsiyalar soni?",
            [
                "A) WHERE sana = ... va COUNT(*)",
                "B) DROP COUNT sana",
                "C) CREATE COUNT sana",
                "D) USER COUNT sana",
            ],
            "A",
            "To‘g‘ri javob: A. Filtrlash + sanash.",
        ),
        _q(
            10,
            "Vaqt vs sana",
            "Faqat sana (kun) bo‘yicha guruhlashda nima e’tiborli?",
            [
                "A) Vaqt qismi kerak bo‘lsa alohida ishlov",
                "B) Hech narsa muhim emas",
                "C) Faqat rang",
                "D) Faqat shrift",
            ],
            "A",
            "To‘g‘ri javob: A. DATETIME bo‘lsa kunni ajratish kerak bo‘lishi mumkin.",
            "medium",
        ),
        _q(
            11,
            "Amaliy",
            "«30 kunlik faollik» tipidagi masala asosan nima bilan bog‘liq?",
            [
                "A) Sana oralig‘i + guruhlash/sanash",
                "B) Faqat DROP TABLE",
                "C) Faqat CREATE USER",
                "D) Faqat GRANT",
            ],
            "A",
            "To‘g‘ri javob: A. Sana filtri va agregat.",
        ),
    ],
    "window-functions": [
        _q(
            1,
            "Window nima?",
            "Window funksiya nima qiladi?",
            [
                "A) Qatorlarni siqmasdan, oynada hisoblaydi",
                "B) Jadvalni o‘chiradi",
                "C) Foydalanuvchi yaratadi",
                "D) Backup oladi",
            ],
            "A",
            "To‘g‘ri javob: A. OVER() — window hisobi, GROUP BY kabi qatorlarni «yig‘maydi».",
        ),
        _q(
            2,
            "OVER",
            "ROW_NUMBER() OVER (ORDER BY amount DESC) da OVER nima?",
            [
                "A) Hisob oynasi / tartib qoidasi",
                "B) Jadval nomi",
                "C) Parol",
                "D) IP",
            ],
            "A",
            "To‘g‘ri javob: A. OVER — window aniqlaydi.",
        ),
        _q(
            3,
            "ROW_NUMBER",
            "ROW_NUMBER() nima beradi?",
            [
                "A) Har qatorga tartib raqami (1,2,3...)",
                "B) Yig‘indi",
                "C) O‘rtacha",
                "D) Jadval nomi",
            ],
            "A",
            "To‘g‘ri javob: A. Qator raqami.",
        ),
        _q(
            4,
            "RANK",
            "RANK() ning xususiyati?",
            [
                "A) Teng qiymatlarga bir xil o‘rin, keyin bo‘shliq qoldirishi mumkin",
                "B) Doim 0 qaytaradi",
                "C) Jadval o‘chiradi",
                "D) Faqat matn qaytaradi",
            ],
            "A",
            "To‘g‘ri javob: A. RANK — tenglikda bir xil rank.",
            "medium",
        ),
        _q(
            5,
            "SUM OVER",
            "SUM(amount) OVER () nima berishi mumkin?",
            [
                "A) Har qatorda umumiy yig‘indi",
                "B) Faqat bitta qator",
                "C) Jadval drop",
                "D) User create",
            ],
            "A",
            "To‘g‘ri javob: A. Window agregat — qatorlar saqlanadi.",
        ),
        _q(
            6,
            "GROUP BY farqi",
            "Window va GROUP BY farqi?",
            [
                "A) Window qatorlarni saqlaydi, GROUP BY yig‘adi",
                "B) Farq yo‘q",
                "C) Window jadval o‘chiradi",
                "D) GROUP BY faqat UI",
            ],
            "A",
            "To‘g‘ri javob: A. Asosiy farq — qatorlar saqlanishi.",
            "medium",
        ),
        _q(
            7,
            "Top-N",
            "Eng katta 3 to‘lovni olishda tipik usul?",
            [
                "A) ROW_NUMBER/RANK + tashqi filtr (rn <= 3)",
                "B) DROP TOP 3",
                "C) CREATE TOP 3",
                "D) USER TOP 3",
            ],
            "A",
            "To‘g‘ri javob: A. Raqamlab, keyin filtr.",
            "medium",
        ),
        _q(
            8,
            "ORDER BY window ichida",
            "OVER (ORDER BY amount DESC) nima uchun?",
            [
                "A) Oyna ichida tartib belgilash",
                "B) Jadval drop",
                "C) User create",
                "D) Grant",
            ],
            "A",
            "To‘g‘ri javob: A. Window tartibi ORDER BY bilan.",
        ),
        _q(
            9,
            "PARTITION BY",
            "PARTITION BY customer_id nima qiladi?",
            [
                "A) Hisobni mijoz bo‘yicha bo‘lib yuritadi",
                "B) Mijozni o‘chiradi",
                "C) Mijoz yaratadi",
                "D) Parol beradi",
            ],
            "A",
            "To‘g‘ri javob: A. Har guruh uchun alohida oyna.",
            "hard",
        ),
        _q(
            10,
            "Qachon kerak",
            "Har qatorda reyting kerak bo‘lsa nima mos?",
            [
                "A) Window funksiya (RANK/ROW_NUMBER)",
                "B) Faqat DROP",
                "C) Faqat CREATE USER",
                "D) Faqat GRANT",
            ],
            "A",
            "To‘g‘ri javob: A. Reyting — window.",
        ),
        _q(
            11,
            "Natija qatorlari",
            "SELECT ..., ROW_NUMBER() OVER (...) FROM t; nechta qator?",
            [
                "A) Asosan t dagi qatorlar sonicha",
                "B) Doim 1",
                "C) Doim 0",
                "D) Doim 100",
            ],
            "A",
            "To‘g‘ri javob: A. Window qatorlarni siqmaydi.",
        ),
    ],
    "advanced-sql": [
        _q(
            1,
            "NULL nima?",
            "NULL nimani anglatadi?",
            [
                "A) Noma’lum / qiymat yo‘q",
                "B) Nol (0) bilan bir xil",
                "C) Bo‘sh matn '' bilan doim bir xil",
                "D) True",
            ],
            "A",
            "To‘g‘ri javob: A. NULL — noma’lum qiymat.",
        ),
        _q(
            2,
            "IS NULL",
            "NULL ni tekshirish uchun to‘g‘ri yozuv?",
            [
                "A) WHERE ustun IS NULL",
                "B) WHERE ustun = NULL",
                "C) WHERE ustun == NULL",
                "D) WHERE ustun EQUAL NULL",
            ],
            "A",
            "To‘g‘ri javob: A. NULL uchun IS NULL / IS NOT NULL.",
        ),
        _q(
            3,
            "COALESCE",
            "COALESCE(amount, 0) nima qiladi?",
            [
                "A) amount NULL bo‘lsa 0 qaytaradi",
                "B) amount ni o‘chiradi",
                "C) Jadval yaratadi",
                "D) User yaratadi",
            ],
            "A",
            "To‘g‘ri javob: A. COALESCE — birinchi NULL bo‘lmagan qiymat.",
        ),
        _q(
            4,
            "Combine tables",
            "Ikki jadvalni birlashtirib, mos kelmasa ham chapni saqlash?",
            [
                "A) LEFT JOIN",
                "B) Faqat INNER JOIN",
                "C) DROP JOIN",
                "D) USER JOIN",
            ],
            "A",
            "To‘g‘ri javob: A. Combine Two Tables — ko‘pincha LEFT JOIN.",
        ),
        _q(
            5,
            "Murakkab so‘rov",
            "JOIN + GROUP BY + filtr tipik tartibi?",
            [
                "A) FROM/JOIN → WHERE → GROUP BY → HAVING → ORDER BY",
                "B) HAVING → FROM → SELECT",
                "C) ORDER BY → FROM → WHERE",
                "D) DROP → JOIN → WHERE",
            ],
            "A",
            "To‘g‘ri javob: A. Standart mantiqiy tartib.",
            "medium",
        ),
        _q(
            6,
            "Debit ulushi",
            "Ulush (foiz) hisoblashda ko‘p ishlatiladigan g‘oya?",
            [
                "A) Kerakli son / jami * 100",
                "B) Faqat DROP",
                "C) Faqat CREATE USER",
                "D) Faqat GRANT",
            ],
            "A",
            "To‘g‘ri javob: A. Foiz = qism / butun.",
            "medium",
        ),
        _q(
            7,
            "CASE shartli sanash",
            "Debitlarni 1, qolganini 0 qilib sanash — qaysi vosita?",
            [
                "A) CASE WHEN ... THEN 1 ELSE 0",
                "B) DROP WHEN",
                "C) CREATE WHEN",
                "D) USER WHEN",
            ],
            "A",
            "To‘g‘ri javob: A. Shartli 1/0 — CASE.",
        ),
        _q(
            8,
            "NULL solishtirish",
            "Nima uchun WHERE x = NULL ishonchsiz?",
            [
                "A) NULL bilan = natijasi noma’lum (NULL)",
                "B) = operatori yo‘q",
                "C) WHERE ishlamaydi",
                "D) NULL degan so‘z yo‘q",
            ],
            "A",
            "To‘g‘ri javob: A. NULL uchun IS NULL.",
            "medium",
        ),
        _q(
            9,
            "Yakuniy takrorlash",
            "Mijoz bo‘yicha tranzaksiyalar soni uchun tipik vositalar?",
            [
                "A) JOIN + GROUP BY + COUNT",
                "B) Faqat DROP TABLE",
                "C) Faqat CREATE USER",
                "D) Faqat GRANT",
            ],
            "A",
            "To‘g‘ri javob: A. Bog‘lash + guruhlash + sanash.",
        ),
        _q(
            10,
            "COALESCE zanjiri",
            "COALESCE(a, b, c) qanday ishlaydi?",
            [
                "A) Chapdan birinchi NULL bo‘lmagan qiymatni oladi",
                "B) Oxirgisini doim oladi",
                "C) Hammasini qo‘shadi",
                "D) Hammasini o‘chiradi",
            ],
            "A",
            "To‘g‘ri javob: A. Chapdan birinchi non-NULL.",
        ),
        _q(
            11,
            "Amaliy maslahat",
            "Murakkab masalada eng yaxshi yondashuv?",
            [
                "A) Bosqichma-bosqich: filtr → bog‘lash → guruh → tekshiruv",
                "B) Tasodifiy yozish",
                "C) Faqat * tanlash",
                "D) Hech narsani tekshirmaslik",
            ],
            "A",
            "To‘g‘ri javob: A. Bosqichma-bosqich yechish.",
        ),
    ],
}


def skill_tests_for_module(module_slug: str) -> list[dict]:
    items = MODULE_SKILL_TESTS.get(module_slug, [])
    result = []
    for item in items:
        data = dict(item)
        num = data.pop("num")
        data["slug"] = f"bt-{module_slug}-{num:02d}"
        result.append(data)
    return result
