# Generated by Django 5.1.8 on 2026-08-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('allowed', 'Ruxsat berilgan'), ('blocked', 'Bloklangan')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi kontent ruxsati',
                'verbose_name_plural': 'Foydalanuvchi kontent ruxsatlari',
            },
        ),
    ]
