# Generated by Django 5.1.8 on 2026-08-16 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontentaccess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercontentaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usercontentaccess',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='access_user_user_id_9aed2d_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentaccess',
            index=models.Index(fields=['status'], name='access_user_status_02cfd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercontentaccess',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uniq_user_content_access'),
        ),
    ]
